import { DashboardRole, DashboardWidgetConfig } from "./widget-types";

export const MASTER_WIDGET_CATALOG: DashboardWidgetConfig[] = [
  // ── COMMAND ────────────────────────────────────────────────
  {
    id: "command-center-alerts",
    title: "Critical Alerts & Attention Items",
    description: "Unified alert feed — overdue events, low stock, AI warnings, approvals",
    defaultVisible: true,
    category: "command",
    order: 1,
  },
  // ── KPI ────────────────────────────────────────────────────
  {
    id: "smart-kpi-summary",
    title: "Key Performance Indicators",
    description: "Role-tuned metrics: cattle, investment, revenue, net P&L with trends",
    defaultVisible: true,
    category: "kpi",
    order: 2,
  },
  // ── OPERATIONS ─────────────────────────────────────────────
  {
    id: "quick-actions-bar",
    title: "Quick Action Center",
    description: "One-tap data capture — add cattle, record cost, vaccination, invoice, AI",
    defaultVisible: true,
    category: "operations",
    order: 3,
  },
  {
    id: "today-tasks-agenda",
    title: "Today's Tasks & Overdue Items",
    description: "Vaccinations, weigh-ins, low stock, loan payments — prioritized by urgency",
    defaultVisible: true,
    category: "operations",
    order: 4,
  },
  // ── FINANCIAL ──────────────────────────────────────────────
  {
    id: "cash-balance-overview",
    title: "Cash Balance & Ledger",
    description: "Live bank balance with inflow / outflow breakdown and cattle asset context",
    defaultVisible: true,
    category: "financial",
    minRole: ["owner", "manager", "accountant", "partner"],
    order: 5,
  },
  {
    id: "revenue-cost-trajectory",
    title: "Revenue vs Cost Trajectory",
    description: "6-month interactive area chart with monthly profit overlay",
    defaultVisible: true,
    category: "financial",
    minRole: ["owner", "manager", "accountant", "partner"],
    order: 6,
  },
  // ── LIVESTOCK ──────────────────────────────────────────────
  {
    id: "herd-valuation",
    title: "Live Herd Valuation",
    description: "Real-time market value, cost basis, unrealized profit and ready-to-sell cattle",
    defaultVisible: true,
    category: "livestock",
    order: 7,
  },
  {
    id: "portfolio-health",
    title: "Portfolio Health Score",
    description: "Composite gauge — FCR, days-in-pen, feed coverage with tier rating",
    defaultVisible: true,
    category: "health",
    order: 8,
  },
  // ── INVENTORY ──────────────────────────────────────────────
  {
    id: "feed-stock-projection",
    title: "Feed Stock & Days Remaining",
    description: "Daily consumption rate, stock runway countdown and restock alerts",
    defaultVisible: true,
    category: "inventory",
    minRole: ["owner", "manager", "veterinarian", "staff"],
    order: 9,
  },
  // ── AI ─────────────────────────────────────────────────────
  {
    id: "ai-advisor",
    title: "Smart Farm Advisor (AI)",
    description: "Natural-language farm queries — daily tasks, feed status, sell advice, health",
    defaultVisible: true,
    category: "ai",
    order: 10,
  },
  {
    id: "smart-insights",
    title: "AI-Generated Insights",
    description: "Auto-discovered anomalies, sell-ready cattle, low-stock warnings",
    defaultVisible: true,
    category: "ai",
    order: 11,
  },
  // ── ANALYTICS ──────────────────────────────────────────────
  {
    id: "cash-flow-forecast",
    title: "Cash Flow Forecast",
    description: "30 / 60 / 90-day revenue projection based on ADG and market price",
    defaultVisible: true,
    category: "analytics",
    minRole: ["owner", "manager", "accountant", "partner"],
    order: 12,
  },
  // ── ACTIVITY ───────────────────────────────────────────────
  {
    id: "activity-audit-feed",
    title: "Recent Activity & Audit Trail",
    description: "Timeline of farm events, transactions, treatments, and system edits",
    defaultVisible: true,
    category: "activity",
    order: 13,
  },
];

/** Role → Default visible widget IDs (ordered by priority for each role) */
export const ROLE_DEFAULT_WIDGETS: Record<DashboardRole, string[]> = {
  owner: [
    "command-center-alerts",
    "smart-kpi-summary",
    "quick-actions-bar",
    "today-tasks-agenda",
    "cash-balance-overview",
    "revenue-cost-trajectory",
    "herd-valuation",
    "portfolio-health",
    "feed-stock-projection",
    "ai-advisor",
    "smart-insights",
    "cash-flow-forecast",
    "activity-audit-feed",
  ],
  manager: [
    "command-center-alerts",
    "smart-kpi-summary",
    "quick-actions-bar",
    "today-tasks-agenda",
    "herd-valuation",
    "portfolio-health",
    "feed-stock-projection",
    "ai-advisor",
    "smart-insights",
    "activity-audit-feed",
  ],
  accountant: [
    "command-center-alerts",
    "smart-kpi-summary",
    "quick-actions-bar",
    "cash-balance-overview",
    "revenue-cost-trajectory",
    "today-tasks-agenda",
    "cash-flow-forecast",
    "smart-insights",
    "activity-audit-feed",
  ],
  veterinarian: [
    "command-center-alerts",
    "smart-kpi-summary",
    "portfolio-health",
    "today-tasks-agenda",
    "quick-actions-bar",
    "feed-stock-projection",
    "ai-advisor",
    "smart-insights",
    "activity-audit-feed",
  ],
  staff: [
    "command-center-alerts",
    "today-tasks-agenda",
    "quick-actions-bar",
    "feed-stock-projection",
    "activity-audit-feed",
  ],
  partner: [
    "smart-kpi-summary",
    "cash-balance-overview",
    "revenue-cost-trajectory",
    "portfolio-health",
    "herd-valuation",
    "cash-flow-forecast",
    "smart-insights",
    "activity-audit-feed",
  ],
};
