/** Words of the stock page's new layout (the rest comes from the dictionary: t.inventory_home). */
export const VIEW_TEXT = {
  en: {
    subtitle: "Buy → mix → feed (deducted daily) → count any time",
    buy: "Buy", mix: "Make a mix", add_item: "Add item", more: "More",
    links_title: "Other pages",
    // to-do
    todo_title: "Needs attention", todo_none: "All good — nothing needs doing now.",
    todo_out: "The chart says the stock has run out — count it or enter the purchase",
    todo_negative: "Stock is below zero ({qty}) — count it to correct the books",
    todo_low_days: "≈ {days} days left",
    todo_low_level: "Low — {qty} left (at its alert level)",
    todo_idle: "In stock for {days} days but not started — nothing is deducted",
    todo_not_started: "In stock, not started — nothing is deducted",
    todo_waiting: "Waiting to be mixed",
    do_count: "Count", do_buy: "Buy", do_start: "Start using", do_mix: "Make a mix",
    // stock
    stock_title: "Stock", tab_feed: "Feed", tab_ingredient: "Ingredients", tab_other: "Medicine & other",
    tab_feed_sub: "Mixes and feed given as it is — deducted every day while in use.",
    tab_ingredient_sub: "Bought to be mixed — they leave stock when a mix is made.",
    tab_other_sub: "Used or finished by hand.",
    search: "Search stock…", no_match: "Nothing matches “{q}”.",
    show_finished: "Show finished ({n})", hide_finished: "Hide finished",
    none_in_tab: "Nothing in stock here.", retired: "Retired items ({n})",
    select: "Select", select_done: "Done", select_all: "Select all", selected: "{n} selected",
    clear: "Clear", finish: "Finished",
    col_item: "Item", col_stock: "Stock", col_value: "Value", col_status: "Status",
    // chips
    chip_in_use: "In use", chip_not_started: "Not started", chip_waiting: "Waiting to mix", chip_mixed: "Mixed",
    chip_finished: "Finished", chip_low: "Low", chip_negative: "Below zero", chip_mix: "Mix", chip_retired: "Retired",
    days_left: "≈ {days} days left", mixed_on: "Went into a mix on {date}", mixed_into: "Went into {mix} on {date}",
    per: "/", no_price: "no price",
    // row menu
    m_buy: "Buy", m_own: "From own land", m_use: "Log use", m_count: "Count check", m_start: "Start using",
    m_finish: "Mark finished", m_history: "History", m_edit: "Edit", m_delete: "Delete", m_restore: "Restore",
    m_delete_blocked: "Delete — finish it first", actions_for: "Actions for {name}",
    del_title: "Delete “{name}”?", del_body: "It is hidden from the list; every purchase and use stays in the history.",
    del_ok: "“{name}” deleted", restore_ok: "“{name}” restored", cancel: "Cancel",
    // recent
    recent_more: "Full history →",
  },
  bn: {
    subtitle: "কিনুন → মিক্স → খাওয়ান (প্রতিদিন নিজে কাটা হয়) → যেকোনো সময় গুনে মেলান",
    buy: "কিনুন", mix: "মিক্স তৈরি", add_item: "জিনিস যোগ", more: "আরও",
    links_title: "অন্য পাতা",
    todo_title: "যা করতে হবে", todo_none: "সব ঠিক আছে — এখন কিছু করার নেই।",
    todo_out: "চার্ট অনুযায়ী স্টক শেষ — গুনে দেখুন, বা কেনার এন্ট্রি দিন",
    todo_negative: "স্টক শূন্যের নিচে ({qty}) — গুনে খাতা ঠিক করুন",
    todo_low_days: "আর ≈ {days} দিন",
    todo_low_level: "কম — বাকি {qty} (সতর্কসীমায়)",
    todo_idle: "{days} দিন ধরে স্টকে, চালু হয়নি — কিছু কাটা হচ্ছে না",
    todo_not_started: "স্টকে আছে, চালু হয়নি — কিছু কাটা হচ্ছে না",
    todo_waiting: "মেশানোর অপেক্ষায়",
    do_count: "গুনুন", do_buy: "কিনুন", do_start: "চালু করুন", do_mix: "মিক্স করুন",
    stock_title: "স্টক", tab_feed: "খাবার", tab_ingredient: "উপকরণ", tab_other: "ওষুধ ও অন্যান্য",
    tab_feed_sub: "মিক্স আর সরাসরি দেওয়া খাবার — চালু থাকলে প্রতিদিন কাটা হয়।",
    tab_ingredient_sub: "মেশানোর জন্য কেনা — মিক্স করলে স্টক থেকে বের হয়।",
    tab_other_sub: "হাতে লিখে ব্যবহার বা শেষ করা হয়।",
    search: "স্টকে খুঁজুন…", no_match: "“{q}” এর সাথে কিছু মেলেনি।",
    show_finished: "শেষ হওয়াগুলো দেখুন ({n})", hide_finished: "শেষ হওয়াগুলো লুকান",
    none_in_tab: "এখানে স্টকে কিছু নেই।", retired: "বন্ধ করা আইটেম ({n})",
    select: "বাছাই", select_done: "হয়েছে", select_all: "সব বাছাই", selected: "{n}টি বাছাই",
    clear: "বাতিল", finish: "শেষ হয়েছে",
    col_item: "জিনিস", col_stock: "স্টক", col_value: "মূল্য", col_status: "অবস্থা",
    chip_in_use: "চালু", chip_not_started: "চালু নেই", chip_waiting: "মেশানোর অপেক্ষায়", chip_mixed: "মিক্সে গেছে",
    chip_finished: "শেষ", chip_low: "কম", chip_negative: "শূন্যের নিচে", chip_mix: "মিক্স", chip_retired: "বন্ধ",
    days_left: "আর ≈ {days} দিন", mixed_on: "{date} মিক্সে গেছে", mixed_into: "{date} {mix}-এ গেছে",
    per: "/", no_price: "দাম নেই",
    m_buy: "কিনুন", m_own: "নিজের জমি থেকে", m_use: "ব্যবহার লিখুন", m_count: "গুনে মেলান", m_start: "ব্যবহার শুরু",
    m_finish: "শেষ হয়েছে", m_history: "ইতিহাস", m_edit: "বদলান", m_delete: "মুছুন", m_restore: "আবার চালু",
    m_delete_blocked: "মুছুন — আগে শেষ করুন", actions_for: "{name} — কাজ",
    del_title: "“{name}” মুছবেন?", del_body: "তালিকা থেকে লুকানো হবে; কেনা ও ব্যবহারের সব ইতিহাস থেকে যাবে।",
    del_ok: "“{name}” মুছে ফেলা হলো", restore_ok: "“{name}” আবার চালু হলো", cancel: "বাতিল",
    recent_more: "সব ইতিহাস →",
  },
} as const;

export type ViewLang = keyof typeof VIEW_TEXT;
export type ViewText = (typeof VIEW_TEXT)[ViewLang];
export const fillText = (s: string, v: Record<string, string | number>) => s.replace(/\{(\w+)\}/g, (_, k) => String(v[k] ?? ""));
