/** Feed mix page text (Bangla / English); plain module so the server page can read it too. */
export const MIX_TEXT = {
  en: {
    title: "Feed mix",
    subtitle: "Mix the ingredients you bought. Each mix, with its date, is that day's recipe: change the amounts any time, and nothing else needs editing.",
    new_mix: "New mix", date: "Mixed on *", mix_item: "Mix goes into", new_item: "{name} (new)",
    fill: "Fill from", fill_last: "Last mix ({date})", fill_memo: "Memo {date} · {shop}", fill_stock: "Everything in stock",
    ingredient: "Ingredient", qty: "Quantity", in_stock: "in stock {qty}", over: "More than the stock ({qty})",
    share: "{pct}% of the mix", add: "Add ingredient", choose: "Choose…", pcs_kg: "= {kg} kg",
    total: "Mix total", cost: "Cost", per_kg: "per kg of mix", unknown_cost: "cost not known yet",
    vs_last: "vs last mix", note: "Note (optional)", save: "Save mix", saving: "Saving…",
    saved: "Mix saved — {qty} kg of mix added to stock", start_feeding: "Start feeding it", saved_before: "This mix was already saved.",
    err_lines: "Add at least one ingredient with a quantity.", err_over: "Some quantities are more than the stock — enter the purchase first or lower them.",
    stock_title: "Mix in stock", in_use: "In use · about {days} days left", not_in_use: "Not in use yet — start it on the Inventory page",
    chart: "Feeding chart", usage: "Feed usage", no_mix_item: "The first mix makes the item “{name}”.",
    waiting: "Waiting to be mixed", waiting_none: "No ingredient is waiting.",
    history: "Recipe by date (every mix)", history_sub: "Each row is one mix: its ingredients are that day's recipe. ▲▼ shows the change from the mix before.",
    kg_mix: "{qty} kg", per_kg_short: "৳{v}/kg", entered: "entered {date}",
    undo: "Undo", undo_prompt: "Why undo this mix? (kept in the history)", undone: "Undone", undone_ok: "Mix undone — stock restored",
    old_recipes: "Earlier recipes (before mixes by date)", old_active: "used {from} → {until}", old_deleted: "removed",
    empty_history: "No mix yet. Your first mix will appear here with its date and shares.",
  },
  bn: {
    title: "খাবার মিক্স",
    subtitle: "কেনা উপকরণগুলো মিশিয়ে মিক্স বানান। প্রতিটি মিক্স তার তারিখসহ সেদিনের রেসিপি — যখন খুশি পরিমাণ বদলান, আর কিছু এডিট করতে হবে না।",
    new_mix: "নতুন মিক্স", date: "কবে মিশিয়েছেন *", mix_item: "মিক্স যাবে", new_item: "{name} (নতুন)",
    fill: "পূরণ করুন", fill_last: "আগের মিক্সের মতো ({date})", fill_memo: "মেমো {date} · {shop}", fill_stock: "স্টকে যা আছে সব",
    ingredient: "উপকরণ", qty: "পরিমাণ", in_stock: "স্টকে {qty}", over: "স্টকের চেয়ে বেশি ({qty})",
    share: "মিক্সের {pct}%", add: "উপকরণ যোগ করুন", choose: "বাছাই করুন…", pcs_kg: "= {kg} kg",
    total: "মোট মিক্স", cost: "খরচ", per_kg: "প্রতি kg মিক্স", unknown_cost: "খরচ এখনো জানা নেই",
    vs_last: "আগের মিক্সের তুলনায়", note: "নোট (ঐচ্ছিক)", save: "মিক্স সেভ করুন", saving: "সেভ হচ্ছে…",
    saved: "মিক্স সেভ হলো — {qty} kg মিক্স স্টকে যোগ হলো", start_feeding: "খাওয়ানো শুরু করুন", saved_before: "এই মিক্স আগেই সেভ হয়েছে।",
    err_lines: "অন্তত একটি উপকরণের পরিমাণ দিন।", err_over: "কিছু পরিমাণ স্টকের চেয়ে বেশি — আগে কেনার এন্ট্রি দিন বা পরিমাণ কমান।",
    stock_title: "স্টকে মিক্স", in_use: "চলছে · আর প্রায় {days} দিন চলবে", not_in_use: "এখনো চালু হয়নি — স্টক পেজ থেকে চালু করুন",
    chart: "খাবারের চার্ট", usage: "খাবার ব্যবহার", no_mix_item: "প্রথম মিক্সে “{name}” আইটেম তৈরি হবে।",
    waiting: "মেশানোর অপেক্ষায়", waiting_none: "কোনো উপকরণ অপেক্ষায় নেই।",
    history: "তারিখ অনুযায়ী রেসিপি (প্রতিটি মিক্স)", history_sub: "প্রতিটি সারি একটি মিক্স: এর উপকরণই সেদিনের রেসিপি। ▲▼ আগের মিক্সের তুলনায় পরিবর্তন দেখায়।",
    kg_mix: "{qty} kg", per_kg_short: "৳{v}/kg", entered: "এন্ট্রি {date}",
    undo: "বাতিল", undo_prompt: "এই মিক্স কেন বাতিল করছেন? (ইতিহাসে থাকবে)", undone: "বাতিল হয়েছে", undone_ok: "মিক্স বাতিল হলো — স্টক আগের মতো",
    old_recipes: "আগের রেসিপি (তারিখভিত্তিক মিক্সের আগে)", old_active: "{from} → {until} ব্যবহার", old_deleted: "সরানো",
    empty_history: "এখনো কোনো মিক্স নেই। প্রথম মিক্স তারিখ ও ভাগসহ এখানে দেখা যাবে।",
  },
} as const;
export type MixLang = keyof typeof MIX_TEXT;
