/** Purchase memo page text (Bangla / English); plain module so the server page can read it too. */
export const PURCHASE_TEXT = {
  en: {
    title: "Buy feed · purchase memo",
    subtitle: "Enter the shop's memo. Stock and cost update at once; transport is added to each item's cost, and any unpaid amount goes to the shop's due.",
    memo: "Memo", date: "Purchase date *", date_note: "The day you bought it (entering later is fine).",
    shop: "Shop / supplier *", shop_ph: "e.g. Bashundia Mor", shop_due: "Due to this shop now: {amount}", shop_last: "Last memo {date}",
    same_memo: "A memo from {shop} on {date} is already entered ({count} items, {amount}). Is this the same memo?", see_it: "See it",
    fill_last: "Fill from the last memo ({date} · {count} items)", fill_last_note: "Items and quantities are filled in; check the prices and quantities.",
    items: "Items", quick_add: "Quick add", add_item: "Add another item",
    item: "Item", search: "Search or type a new item…", create: "Add new item “{name}”", no_items: "No match",
    new_item: "New item", category: "Category", unit: "Unit", kg_per_unit: "1 {unit} = ? kg (optional)",
    qty: "Quantity", bags: "By bags", bags_n: "Bags", kg_per_bag: "kg / bag",
    price: "Price", price_total: "Total ৳", price_unit: "৳ per {unit}",
    line_total: "Total {amount}", per_unit: "{amount}/{unit}", landed: "with transport {amount}/{unit}",
    last: "Last bought {amount}/{unit} · {date}", up: "▲ {pct}% dearer", down: "▼ {pct}% cheaper",
    zero_price: "Price is 0 — only if it was free.", big_change: "Price differs a lot from last time — please check.",
    remove: "Remove item",
    transport: "Transport / loading ৳", transport_note: "Shared over the items by their price.", notes: "Note", notes_ph: "Optional",
    payment: "Payment", cash: "Paid in full", partial: "Part paid", due: "All due", paid_now: "Paid now ৳ *",
    due_note: "{amount} will be added to {shop}'s due.",
    summary: "Memo total", items_total: "Items", transport_short: "Transport", total: "Total bill", paid: "Paid", due_amount: "Due",
    save: "Save memo", saving: "Saving…", saved: "Memo saved — stock updated", view_stock: "View stock", saved_before: "This memo was already saved.",
    confirm_zero: "Some items have price 0. Save anyway?",
    err_qty: "Enter a quantity for every item.", err_item: "Choose an item in every row.", err_new: "Give the new item a name.", err_paid: "Paid amount is more than the bill.",
    recent: "Recent memos", recent_all: "All purchase history", entered: "entered {date}", items_n: "{count} items",
    empty_recent: "No memo yet.",
    cats: { feed: "Feed", roughage: "Roughage", medicine: "Medicine", equipment: "Equipment", other: "Other" },
  },
  bn: {
    title: "খাবার কেনা · মেমো",
    subtitle: "দোকানের মেমো থেকে এন্ট্রি দিন। স্টক ও খরচ সাথে সাথে হিসাব হয়; গাড়ি ভাড়া প্রতিটি আইটেমের দামে যোগ হয়, আর বাকি থাকলে দোকানের বাকিতে যায়।",
    memo: "মেমো", date: "কেনার তারিখ *", date_note: "যেদিন কিনেছেন (পরে এন্ট্রি দিলেও চলবে)।",
    shop: "দোকান / সরবরাহকারী *", shop_ph: "যেমন Bashundia Mor", shop_due: "এই দোকানে এখন বাকি: {amount}", shop_last: "শেষ মেমো {date}",
    same_memo: "{shop}-এর {date} তারিখের একটি মেমো আগেই এন্ট্রি হয়েছে ({count}টি আইটেম, {amount})। এটা কি একই মেমো?", see_it: "দেখুন",
    fill_last: "আগের মেমো থেকে পূরণ করুন ({date} · {count}টি আইটেম)", fill_last_note: "আইটেম ও পরিমাণ বসানো হলো; দাম আর পরিমাণ মিলিয়ে নিন।",
    items: "আইটেম", quick_add: "দ্রুত যোগ", add_item: "আরেকটি আইটেম",
    item: "আইটেম", search: "খুঁজুন বা নতুন আইটেমের নাম লিখুন…", create: "নতুন আইটেম “{name}” যোগ করুন", no_items: "মিলছে না",
    new_item: "নতুন আইটেম", category: "ধরন", unit: "একক", kg_per_unit: "১ {unit} = কত kg? (ঐচ্ছিক)",
    qty: "পরিমাণ", bags: "বস্তা হিসাবে", bags_n: "বস্তা", kg_per_bag: "kg / বস্তা",
    price: "দাম", price_total: "মোট ৳", price_unit: "প্রতি {unit} ৳",
    line_total: "মোট {amount}", per_unit: "{amount}/{unit}", landed: "ভাড়াসহ {amount}/{unit}",
    last: "শেষ কেনা {amount}/{unit} · {date}", up: "▲ {pct}% বেশি", down: "▼ {pct}% কম",
    zero_price: "দাম 0 — বিনা মূল্যে পেলে তবেই ঠিক।", big_change: "আগের দামের সাথে অনেক পার্থক্য — একবার দেখে নিন।",
    remove: "আইটেম বাদ দিন",
    transport: "গাড়ি ভাড়া / লোডিং ৳", transport_note: "দাম অনুযায়ী আইটেমগুলোর মধ্যে ভাগ হবে।", notes: "নোট", notes_ph: "ঐচ্ছিক",
    payment: "টাকা দেওয়া", cash: "পুরো নগদ", partial: "কিছু দিয়েছি", due: "পুরোটা বাকি", paid_now: "এখন দিয়েছি ৳ *",
    due_note: "{amount} {shop}-এর বাকিতে যোগ হবে।",
    summary: "মেমোর হিসাব", items_total: "আইটেম", transport_short: "গাড়ি ভাড়া", total: "মোট বিল", paid: "দেওয়া হলো", due_amount: "বাকি",
    save: "মেমো সেভ করুন", saving: "সেভ হচ্ছে…", saved: "মেমো সেভ হলো — স্টক আপডেট হয়েছে", view_stock: "স্টক দেখুন", saved_before: "এই মেমো আগেই সেভ হয়েছে।",
    confirm_zero: "কিছু আইটেমের দাম 0। তবুও সেভ করবেন?",
    err_qty: "প্রতিটি আইটেমের পরিমাণ দিন।", err_item: "প্রতিটি সারিতে আইটেম বাছুন।", err_new: "নতুন আইটেমের নাম দিন।", err_paid: "দেওয়া টাকা বিলের চেয়ে বেশি।",
    recent: "সাম্প্রতিক মেমো", recent_all: "সব কেনার ইতিহাস", entered: "এন্ট্রি {date}", items_n: "{count}টি আইটেম",
    empty_recent: "এখনো কোনো মেমো নেই।",
    cats: { feed: "দানাদার খাবার", roughage: "খড়-ঘাস", medicine: "ওষুধ", equipment: "যন্ত্রপাতি", other: "অন্যান্য" },
  },
} as const;
export type PurchaseLang = keyof typeof PURCHASE_TEXT;
