import type { ExecutiveRoleSlug, RoleDashboardConfig } from "./types";

export class RoleDashboardService {
  private static roleConfigs: Record<ExecutiveRoleSlug, RoleDashboardConfig> = {
    ceo: {
      roleSlug: "ceo",
      roleTitle: "Chief Executive Officer (CEO)",
      description: "Executive macro indicators, farm valuation, ROI, profitability, and enterprise risk oversight.",
      primaryKpis: ["netFarmProfit", "grossMarginPercent", "totalBiologicalAssetValue", "totalRevenue", "farmRoiPercent", "cashRunwayDays"],
      allowedExportFormats: ["pdf", "excel", "csv"],
      defaultWidgets: [
        {
          id: "ceo-financial-kpis",
          title: "Executive Financial Health",
          widgetType: "kpi_card",
          dataSource: "finance",
          queryConfig: {},
          displayConfig: { format: "currency" },
          positionX: 0,
          positionY: 0,
          width: 12,
          height: 3,
        },
        {
          id: "ceo-revenue-profit-trend",
          title: "Revenue vs Expense & Net Margin Trend",
          widgetType: "line_chart",
          dataSource: "finance",
          queryConfig: { timeRange: "6m" },
          displayConfig: { colorTheme: "emerald" },
          positionX: 0,
          positionY: 3,
          width: 8,
          height: 5,
        },
        {
          id: "ceo-asset-breakdown",
          title: "Asset Valuation Composition",
          widgetType: "pie_chart",
          dataSource: "finance",
          queryConfig: {},
          displayConfig: {},
          positionX: 8,
          positionY: 3,
          width: 4,
          height: 5,
        },
        {
          id: "ceo-critical-alerts",
          title: "Executive Alert & Risk Feed",
          widgetType: "alert_feed",
          dataSource: "kpi_engine",
          queryConfig: { minSeverity: "high" },
          displayConfig: {},
          positionX: 0,
          positionY: 8,
          width: 12,
          height: 4,
        },
      ],
    },
    farm_manager: {
      roleSlug: "farm_manager",
      roleTitle: "Farm Manager",
      description: "Operational herd management, daily growth rates, feed conversion efficiency, and barn logistics.",
      primaryKpis: ["activeHeadCount", "averageDailyGainKg", "feedConversionRatio", "totalLiveBiomassKg", "averageDaysOnFeed", "mortalityRatePercent"],
      allowedExportFormats: ["pdf", "excel", "csv"],
      defaultWidgets: [
        {
          id: "fm-herd-summary",
          title: "Livestock & Biomass Summary",
          widgetType: "kpi_card",
          dataSource: "livestock",
          queryConfig: {},
          displayConfig: {},
          positionX: 0,
          positionY: 0,
          width: 12,
          height: 3,
        },
        {
          id: "fm-growth-distribution",
          title: "Average Daily Gain (ADG) by Breed & Batch",
          widgetType: "bar_chart",
          dataSource: "livestock",
          queryConfig: {},
          displayConfig: { unit: "kg/day" },
          positionX: 0,
          positionY: 3,
          width: 6,
          height: 5,
        },
      ],
    },
    veterinarian: {
      roleSlug: "veterinarian",
      roleTitle: "Veterinarian & Herd Health Officer",
      description: "Clinical health compliance, vaccination schedules, quarantine logs, and drug withdrawal restrictions.",
      primaryKpis: ["vaccinationComplianceRate", "treatmentSuccessRate", "activeWithdrawalCount", "overdueMedicalEventsCount", "quarantinedCount", "activeTreatmentsCount"],
      allowedExportFormats: ["pdf", "excel", "csv"],
      defaultWidgets: [
        {
          id: "vet-health-kpis",
          title: "Veterinary Compliance Scorecard",
          widgetType: "kpi_card",
          dataSource: "health",
          queryConfig: {},
          displayConfig: {},
          positionX: 0,
          positionY: 0,
          width: 12,
          height: 3,
        },
      ],
    },
    finance_manager: {
      roleSlug: "finance_manager",
      roleTitle: "Finance & Accounting Manager",
      description: "GAAP financial statements, cash flow runway, cost per kg liveweight gain, and budget allocations.",
      primaryKpis: ["totalRevenue", "totalOperatingExpense", "netFarmProfit", "cashRunwayDays", "costPerKgGain", "breakEvenPricePerKg"],
      allowedExportFormats: ["pdf", "excel", "csv"],
      defaultWidgets: [
        {
          id: "fin-pnl-overview",
          title: "Financial Ledger & Unit Economics",
          widgetType: "kpi_card",
          dataSource: "finance",
          queryConfig: {},
          displayConfig: { format: "currency" },
          positionX: 0,
          positionY: 0,
          width: 12,
          height: 3,
        },
      ],
    },
    inventory_manager: {
      roleSlug: "inventory_manager",
      roleTitle: "Inventory & Warehouse Manager",
      description: "Feed ingredients, veterinary supplies, stock valuations, and reorder point monitoring.",
      primaryKpis: ["totalStockValuation", "lowStockItemsCount", "criticalStockOutCount", "dailyFeedRunRateKg", "inventoryTurnoverRatio", "feedStockRunwayDays"],
      allowedExportFormats: ["pdf", "excel", "csv"],
      defaultWidgets: [
        {
          id: "inv-summary",
          title: "Warehouse & Feed Stock Overview",
          widgetType: "kpi_card",
          dataSource: "inventory",
          queryConfig: {},
          displayConfig: {},
          positionX: 0,
          positionY: 0,
          width: 12,
          height: 3,
        },
      ],
    },
    operations_manager: {
      roleSlug: "operations_manager",
      roleTitle: "Operations Manager",
      description: "Facility operations, batch logistics, daily task schedules, and operational continuity.",
      primaryKpis: ["activeHeadCount", "unweighedCattleCount", "quarantinedCount", "dailyFeedRunRateKg", "lowStockItemsCount", "overdueMedicalEventsCount"],
      allowedExportFormats: ["pdf", "excel", "csv"],
      defaultWidgets: [
        {
          id: "ops-summary",
          title: "Daily Operations Status",
          widgetType: "kpi_card",
          dataSource: "kpi_engine",
          queryConfig: {},
          displayConfig: {},
          positionX: 0,
          positionY: 0,
          width: 12,
          height: 3,
        },
      ],
    },
    sales_manager: {
      roleSlug: "sales_manager",
      roleTitle: "Commercial & Sales Manager",
      description: "Livestock sales orders, Qurbani booking pipeline, average order value, and customer retention.",
      primaryKpis: ["totalOrdersCount", "totalGrossSalesBdt", "averageOrderValueBdt", "qurbaniBookingsCount", "pendingDeliveriesCount", "repeatCustomerRatePct"],
      allowedExportFormats: ["pdf", "excel", "csv"],
      defaultWidgets: [
        {
          id: "sales-kpis",
          title: "Commercial & Booking Scorecard",
          widgetType: "kpi_card",
          dataSource: "commerce",
          queryConfig: {},
          displayConfig: { format: "currency" },
          positionX: 0,
          positionY: 0,
          width: 12,
          height: 3,
        },
      ],
    },
    system_admin: {
      roleSlug: "system_admin",
      roleTitle: "System & Governance Administrator",
      description: "Multi-tenant integrity, audit trail tracking, RLS policies, snapshot logs, and security compliance.",
      primaryKpis: ["activeHeadCount", "totalRevenue", "overdueMedicalEventsCount", "criticalStockOutCount", "activeWithdrawalCount", "cashRunwayDays"],
      allowedExportFormats: ["pdf", "excel", "csv"],
      defaultWidgets: [
        {
          id: "admin-platform-health",
          title: "System & Tenant Health",
          widgetType: "kpi_card",
          dataSource: "kpi_engine",
          queryConfig: {},
          displayConfig: {},
          positionX: 0,
          positionY: 0,
          width: 12,
          height: 3,
        },
      ],
    },
    custom: {
      roleSlug: "custom",
      roleTitle: "Custom Executive Workspace",
      description: "User customized analytical dashboard with custom widgets and pinned reports.",
      primaryKpis: ["netFarmProfit", "totalBiologicalAssetValue", "activeHeadCount"],
      allowedExportFormats: ["pdf", "excel", "csv"],
      defaultWidgets: [],
    },
  };

  public static getDashboardForRole(roleSlug: ExecutiveRoleSlug): RoleDashboardConfig {
    return this.roleConfigs[roleSlug] || this.roleConfigs.ceo;
  }

  public static getAllRoles(): { slug: ExecutiveRoleSlug; title: string; description: string }[] {
    return Object.values(this.roleConfigs).map((c) => ({
      slug: c.roleSlug,
      title: c.roleTitle,
      description: c.description,
    }));
  }
}
