import { type NutritionPlan } from "./types";

export const PRESET_NUTRITION_PLANS: NutritionPlan[] = [
  {
    id: "plan-intensive-fattening",
    businessId: "system",
    name: "Intensive 90-Day Fattening (High ADG)",
    planType: "weight_based",
    targetStage: "fattener",
    targetAdgKg: 1.25,
    dmiPercentBw: 2.8,
    targetCpPercentDm: 14.5,
    targetTdnPercentDm: 74.0,
    defaultConcentrateRatio: 0.50,
    defaultRoughageRatio: 0.50,
    slots: [
      { slot: "morning", timeOfDay: "07:00", sharePercent: 50 },
      { slot: "evening", timeOfDay: "17:30", sharePercent: 50 },
    ],
    active: true,
    notes: "Designed for bulls in final finishing stage to achieve maximum marbling and live weight gain.",
  },
  {
    id: "plan-post-arrival-acclimatization",
    businessId: "system",
    name: "Post-Arrival Rumen Acclimatization",
    planType: "health_based",
    targetStage: "grower",
    targetAdgKg: 0.6,
    dmiPercentBw: 2.2,
    targetCpPercentDm: 11.5,
    targetTdnPercentDm: 62.0,
    defaultConcentrateRatio: 0.20,
    defaultRoughageRatio: 0.80,
    slots: [
      { slot: "morning", timeOfDay: "07:30", sharePercent: 40 },
      { slot: "noon", timeOfDay: "13:00", sharePercent: 20 },
      { slot: "evening", timeOfDay: "18:00", sharePercent: 40 },
    ],
    active: true,
    notes: "Gradual concentrate ramp up over 14 days to prevent rumen acidosis in newly procured cattle.",
  },
  {
    id: "plan-summer-heat-stress",
    businessId: "system",
    name: "Summer Heat Stress Rumen Shield",
    planType: "custom",
    targetStage: "fattener",
    targetAdgKg: 1.0,
    dmiPercentBw: 2.5,
    targetCpPercentDm: 13.5,
    targetTdnPercentDm: 70.0,
    defaultConcentrateRatio: 0.45,
    defaultRoughageRatio: 0.55,
    slots: [
      { slot: "morning", timeOfDay: "05:30", sharePercent: 45 },
      { slot: "evening", timeOfDay: "19:00", sharePercent: 45 },
      { slot: "night", timeOfDay: "22:30", sharePercent: 10 },
    ],
    active: true,
    notes: "Early morning and late night feeding slots to avoid feeding during peak ambient heat.",
  },
];
