import { WorkflowTemplate } from "./types";

export const FEEDING_TEMPLATE: WorkflowTemplate = {
  id: "wf_daily_feeding",
  code: "FEED-01",
  title: "Daily Feeding Routine",
  shortDescription: "Record daily cattle ration consumption, deduct stock FIFO, and calculate FCR",
  fullDescription: "Consolidated workflow to record morning or evening feeding across cattle batches. Automatically calculates total feed consumed, issues inventory FIFO deductions, posts cost allocations to cattle lots, and updates growth projections.",
  category: "livestock",
  icon: "Utensils",
  estimatedTimeMinutes: 2,
  tags: ["feeding", "livestock", "daily", "inventory"],
  roleAccess: ["owner", "manager", "worker"],
  isPinned: true,
  isFavorite: true,
  clickReductionRatio: "3 steps vs 14 clicks",
  timeOfDaySuggestion: "morning",
  steps: [
    {
      id: "step_feed_select",
      title: "Feed Allocation & Batch",
      description: "Choose cattle group or lot and selected feed ration formula",
      fields: [
        {
          id: "batch_id",
          name: "batch_id",
          label: "Cattle Batch / Shed",
          type: "select",
          required: true,
          options: [
            { label: "Shed A - Fattening Bulls (25 Head)", value: "shed_a" },
            { label: "Shed B - Growing Calves (18 Head)", value: "shed_b" },
            { label: "Shed C - Dairy Cows (12 Head)", value: "shed_c" },
          ],
        },
        {
          id: "feed_item_id",
          name: "feed_item_id",
          label: "Feed Inventory Item",
          type: "select",
          required: true,
          options: [
            { label: "Silage (Corn/Napier) - Stock: 4,200 kg", value: "item_silage" },
            { label: "Total Mixed Ration (TMR) - Stock: 1,850 kg", value: "item_tmr" },
            { label: "Wheat Bran (Choker) - Stock: 920 kg", value: "item_bran" },
          ],
        },
        {
          id: "feeding_shift",
          name: "feeding_shift",
          label: "Shift",
          type: "select",
          required: true,
          defaultValue: "morning",
          options: [
            { label: "Morning Feed (06:00 - 08:00)", value: "morning" },
            { label: "Evening Feed (17:00 - 19:00)", value: "evening" },
          ],
        },
      ],
    },
    {
      id: "step_feed_quantity",
      title: "Quantity Fed",
      description: "Enter net weight fed in kilograms",
      fields: [
        {
          id: "quantity_kg",
          name: "quantity_kg",
          label: "Total Quantity Fed (kg)",
          type: "number",
          required: true,
          min: 1,
          placeholder: "e.g. 150",
        },
        {
          id: "notes",
          name: "notes",
          label: "Observation Notes",
          type: "textarea",
          placeholder: "Appetite level, herd behavior...",
        },
      ],
    },
  ],
  cascadeActions: [
    {
      id: "cascade_feed_inventory",
      type: "update_inventory",
      name: "Inventory Stock Deduction",
      description: "Deducts consumed feed quantity from active inventory lot",
      targetModule: "inventory",
      isCompensatable: true,
      executor: async (ctx) => ({
        success: true,
        actionId: "cascade_feed_inventory",
        actionType: "update_inventory",
        entityId: String(ctx.formData.feed_item_id || "item_silage"),
        entityType: "inventory_item",
        data: { deductedKg: ctx.formData.quantity_kg },
        timestamp: new Date().toISOString(),
      }),
    },
    {
      id: "cascade_feed_activity",
      type: "log_activity",
      name: "Activity Log",
      description: "Logs daily nutrition event against cattle batch health",
      targetModule: "livestock",
      isCompensatable: false,
      executor: async (ctx) => ({
        success: true,
        actionId: "cascade_feed_activity",
        actionType: "log_activity",
        entityId: String(ctx.formData.batch_id || "shed_a"),
        entityType: "cattle_batch",
        data: { shift: ctx.formData.feeding_shift },
        timestamp: new Date().toISOString(),
      }),
    },
  ],
  relatedEntitiesResolver: (data) => [
    {
      id: String(data.batch_id || "shed_a"),
      entityType: "cattle",
      label: `Cattle Batch: ${data.batch_id || "Shed A"}`,
      url: "/dashboard/cattle",
      module: "livestock",
    },
    {
      id: String(data.feed_item_id || "item_silage"),
      entityType: "inventory_item",
      label: `Inventory: ${data.feed_item_id || "Silage"}`,
      url: "/dashboard/inventory",
      module: "inventory",
    },
  ],
};
