import { WorkflowTemplate } from "./types";

export const PURCHASE_FEED_TEMPLATE: WorkflowTemplate = {
  id: "wf_purchase_feed",
  code: "PROC-01",
  title: "Purchase Feed & Fodder",
  shortDescription: "Order feed stock, update FIFO inventory, record expense, and update supplier balance",
  fullDescription: "Automated procurement workflow. Seamlessly increases warehouse stock, creates expense journal entry, recalculates supplier ledger balance, logs farm activity, and sends notification in one go.",
  category: "inventory",
  icon: "Truck",
  estimatedTimeMinutes: 3,
  tags: ["purchase", "feed", "procurement", "inventory", "supplier", "expense"],
  roleAccess: ["owner", "manager", "accountant"],
  isPinned: true,
  isFavorite: true,
  clickReductionRatio: "2 steps vs 18 clicks",
  timeOfDaySuggestion: "anytime",
  steps: [
    {
      id: "step_purchase_vendor",
      title: "Supplier & Item",
      description: "Select supplier and feed inventory product",
      fields: [
        {
          id: "vendor_id",
          name: "vendor_id",
          label: "Feed Supplier",
          type: "select",
          required: true,
          options: [
            { label: "Bengal Agro Feeds Ltd", value: "v_bengal" },
            { label: "Sonali Silage Supply Co", value: "v_sonali" },
          ],
        },
        {
          id: "item_id",
          name: "item_id",
          label: "Inventory Item",
          type: "select",
          required: true,
          options: [
            { label: "Silage (Corn / Napier)", value: "item_silage" },
            { label: "Total Mixed Ration (TMR)", value: "item_tmr" },
          ],
        },
      ],
    },
    {
      id: "step_purchase_financials",
      title: "Quantity & Billing",
      description: "Enter received weight and total price",
      fields: [
        {
          id: "quantity_kg",
          name: "quantity_kg",
          label: "Quantity Purchased (kg)",
          type: "number",
          required: true,
          min: 10,
          placeholder: "e.g. 5000",
        },
        {
          id: "total_amount_bdt",
          name: "total_amount_bdt",
          label: "Total Invoice Amount (BDT)",
          type: "currency",
          required: true,
          placeholder: "e.g. 125000",
        },
        {
          id: "paid_amount_bdt",
          name: "paid_amount_bdt",
          label: "Amount Paid Now (BDT)",
          type: "currency",
          defaultValue: 0,
        },
      ],
    },
  ],
  cascadeActions: [
    {
      id: "cascade_purchase_inventory",
      type: "update_inventory",
      name: "FIFO Stock Inward",
      description: "Adds purchased kilograms to active inventory with unit cost",
      targetModule: "inventory",
      isCompensatable: true,
      executor: async (ctx) => ({
        success: true,
        actionId: "cascade_purchase_inventory",
        actionType: "update_inventory",
        entityId: String(ctx.formData.item_id || "item_silage"),
        data: { addedKg: ctx.formData.quantity_kg },
        timestamp: new Date().toISOString(),
      }),
    },
    {
      id: "cascade_purchase_expense",
      type: "record_expense",
      name: "Post Procurement Expense",
      description: "Creates operational expense entry under Feed & Nutrition",
      targetModule: "finance",
      isCompensatable: true,
      executor: async (ctx) => ({
        success: true,
        actionId: "cascade_purchase_expense",
        actionType: "record_expense",
        data: { amount: ctx.formData.total_amount_bdt },
        timestamp: new Date().toISOString(),
      }),
    },
    {
      id: "cascade_purchase_supplier",
      type: "update_supplier_balance",
      name: "Update Supplier Balance",
      description: "Credits supplier accounts payable balance",
      targetModule: "accounting",
      isCompensatable: true,
      executor: async (ctx) => {
        const total = Number(ctx.formData.total_amount_bdt) || 0;
        const paid = Number(ctx.formData.paid_amount_bdt) || 0;
        return {
          success: true,
          actionId: "cascade_purchase_supplier",
          actionType: "update_supplier_balance",
          entityId: String(ctx.formData.vendor_id || "v_bengal"),
          data: { payableDue: Math.max(0, total - paid) },
          timestamp: new Date().toISOString(),
        };
      },
    },
    {
      id: "cascade_purchase_activity",
      type: "log_activity",
      name: "Activity Audit Log",
      description: "Logs inventory receipt event in audit trail",
      targetModule: "operations",
      isCompensatable: false,
      executor: async (ctx) => ({
        success: true,
        actionId: "cascade_purchase_activity",
        actionType: "log_activity",
        data: { event: "Feed Purchase Received" },
        timestamp: new Date().toISOString(),
      }),
    },
    {
      id: "cascade_purchase_notify",
      type: "dispatch_notification",
      name: "Procurement Notification",
      description: "Alerts management of feed inventory replenishment",
      targetModule: "operations",
      isCompensatable: false,
      executor: async (ctx) => ({
        success: true,
        actionId: "cascade_purchase_notify",
        actionType: "dispatch_notification",
        data: { title: "Feed Restocked" },
        timestamp: new Date().toISOString(),
      }),
    },
  ],
  relatedEntitiesResolver: (data) => [
    {
      id: String(data.vendor_id || "v_bengal"),
      entityType: "vendor",
      label: `Vendor: ${data.vendor_id || "Bengal Agro Feeds"}`,
      url: "/dashboard/vendors",
      module: "inventory",
    },
    {
      id: String(data.item_id || "item_silage"),
      entityType: "inventory_item",
      label: `Stock Item: ${data.item_id || "Silage"}`,
      url: "/dashboard/inventory",
      module: "inventory",
    },
  ],
};
