import { WorkflowTemplate } from "./types";

export const WEIGHT_MEASUREMENT_TEMPLATE: WorkflowTemplate = {
  id: "wf_weight_measurement",
  code: "WT-01",
  title: "Weight Measurement & ADG",
  shortDescription: "Record animal scale weight, compute ADG, and trigger weight loss alerts",
  fullDescription: "Routine live-weight recording workflow. Automatically computes Average Daily Gain (ADG) and alerts if weight drops.",
  category: "livestock",
  icon: "Scale",
  estimatedTimeMinutes: 2,
  tags: ["weight", "growth", "adg", "livestock"],
  roleAccess: ["owner", "manager", "worker"],
  isPinned: true,
  isFavorite: false,
  clickReductionRatio: "1 step vs 8 clicks",
  timeOfDaySuggestion: "morning",
  steps: [
    {
      id: "step_weight_input",
      title: "Scale Recording",
      description: "Enter cattle tag and current scale reading",
      fields: [
        {
          id: "cattle_tag",
          name: "cattle_tag",
          label: "Cattle Ear Tag #",
          type: "text",
          required: true,
          placeholder: "e.g. TAG-101",
        },
        {
          id: "weight_kg",
          name: "weight_kg",
          label: "Current Weight (kg)",
          type: "number",
          required: true,
          min: 20,
          max: 1500,
          placeholder: "e.g. 485.5",
        },
      ],
    },
  ],
  cascadeActions: [
    {
      id: "cascade_weight_update",
      type: "update_cattle_weight",
      name: "Cattle Weight Update",
      description: "Updates animal latest weight and recomputes ADG curve",
      targetModule: "livestock",
      isCompensatable: true,
      executor: async (ctx) => ({
        success: true,
        actionId: "cascade_weight_update",
        actionType: "update_cattle_weight",
        entityId: String(ctx.formData.cattle_tag || "TAG-101"),
        data: { weightKg: ctx.formData.weight_kg },
        timestamp: new Date().toISOString(),
      }),
    },
  ],
  relatedEntitiesResolver: (data) => [
    {
      id: String(data.cattle_tag || "TAG-101"),
      entityType: "cattle",
      label: `Cattle Tag: ${data.cattle_tag || "TAG-101"}`,
      url: "/dashboard/cattle",
      module: "livestock",
    },
  ],
};

export const SELL_ANIMAL_TEMPLATE: WorkflowTemplate = {
  id: "wf_sell_animal",
  code: "SALE-01",
  title: "Sell Animal & Close Batch",
  shortDescription: "Finalize cattle sale, record revenue, compute net ROI, and notify partners",
  fullDescription: "End-to-end cattle divestment workflow. Updates animal status to SOLD, records financial revenue, and triggers partner profit share calculations.",
  category: "livestock",
  icon: "BadgeDollarSign",
  estimatedTimeMinutes: 4,
  tags: ["sales", "livestock", "finance", "revenue", "partner"],
  roleAccess: ["owner", "manager"],
  isPinned: true,
  isFavorite: true,
  clickReductionRatio: "2 steps vs 22 clicks",
  timeOfDaySuggestion: "afternoon",
  steps: [
    {
      id: "step_sale_animal",
      title: "Animal & Buyer",
      description: "Choose cattle tag and buyer details",
      fields: [
        {
          id: "cattle_tag",
          name: "cattle_tag",
          label: "Cattle Ear Tag #",
          type: "text",
          required: true,
          placeholder: "e.g. TAG-101",
        },
        {
          id: "buyer_name",
          name: "buyer_name",
          label: "Buyer / Customer Name",
          type: "text",
          required: true,
          placeholder: "e.g. Al-Madina Meat Processing Ltd",
        },
      ],
    },
    {
      id: "step_sale_financials",
      title: "Sale Price & Settlement",
      description: "Enter negotiated price and payment method",
      fields: [
        {
          id: "sale_price_bdt",
          name: "sale_price_bdt",
          label: "Agreed Sale Price (BDT)",
          type: "currency",
          required: true,
          placeholder: "e.g. 185000",
        },
        {
          id: "final_weight_kg",
          name: "final_weight_kg",
          label: "Exit Weigh-in (kg)",
          type: "number",
          required: true,
          placeholder: "e.g. 520",
        },
      ],
    },
  ],
  cascadeActions: [
    {
      id: "cascade_sale_cattle_status",
      type: "update_cattle_status",
      name: "Update Status to SOLD",
      description: "Marks cattle as exited",
      targetModule: "livestock",
      isCompensatable: true,
      executor: async (ctx) => ({
        success: true,
        actionId: "cascade_sale_cattle_status",
        actionType: "update_cattle_status",
        entityId: String(ctx.formData.cattle_tag || "TAG-101"),
        data: { status: "sold" },
        timestamp: new Date().toISOString(),
      }),
    },
    {
      id: "cascade_sale_income",
      type: "record_income",
      name: "Financial Income Entry",
      description: "Posts revenue journal credit",
      targetModule: "finance",
      isCompensatable: true,
      executor: async (ctx) => ({
        success: true,
        actionId: "cascade_sale_income",
        actionType: "record_income",
        data: { amount: ctx.formData.sale_price_bdt },
        timestamp: new Date().toISOString(),
      }),
    },
  ],
  relatedEntitiesResolver: (data) => [
    {
      id: String(data.cattle_tag || "TAG-101"),
      entityType: "cattle",
      label: `Sold Cattle: ${data.cattle_tag || "TAG-101"}`,
      url: "/dashboard/cattle",
      module: "livestock",
    },
  ],
};
