import { WorkflowTemplate } from "./types";

export const RECORD_EXPENSE_TEMPLATE: WorkflowTemplate = {
  id: "wf_record_expense",
  code: "EXP-01",
  title: "Record Farm Expense",
  shortDescription: "Record operating costs, utilities, labor, or transport with receipt attachment",
  fullDescription: "Standard operational cost entry workflow. Deducts farm cash/bank balances, logs ledger entries, and routes for approval if above threshold.",
  category: "finance",
  icon: "Receipt",
  estimatedTimeMinutes: 2,
  tags: ["expense", "finance", "cost", "cash"],
  roleAccess: ["owner", "manager", "accountant"],
  isPinned: true,
  isFavorite: true,
  clickReductionRatio: "1 step vs 12 clicks",
  timeOfDaySuggestion: "anytime",
  approvalRequirement: {
    requiredRole: ["owner", "manager"],
    minApprovalCount: 1,
    autoApproveBelowAmount: 10000,
    conditionDescription: "Amounts above ৳10,000 require Manager approval",
  },
  steps: [
    {
      id: "step_exp_main",
      title: "Expense Details",
      description: "Specify cost category and payment account",
      fields: [
        {
          id: "cost_category",
          name: "cost_category",
          label: "Category",
          type: "select",
          required: true,
          options: [
            { label: "Electricity & Generator Fuel", value: "utilities" },
            { label: "Labor & Worker Wages", value: "wages" },
            { label: "Transportation & Freight", value: "transport" },
            { label: "Equipment Maintenance", value: "maintenance" },
            { label: "Farm Supplies & Cleaning", value: "supplies" },
          ],
        },
        {
          id: "amount_bdt",
          name: "amount_bdt",
          label: "Amount (BDT)",
          type: "currency",
          required: true,
          placeholder: "e.g. 15000",
        },
        {
          id: "payment_account",
          name: "payment_account",
          label: "Payment Method",
          type: "select",
          required: true,
          options: [
            { label: "Cash in Vault", value: "cash_vault" },
            { label: "Islami Bank Current Account", value: "bank_ibbl" },
            { label: "bKash Business", value: "mfs_bkash" },
          ],
        },
      ],
    },
  ],
  cascadeActions: [
    {
      id: "cascade_exp_entry",
      type: "record_expense",
      name: "Financial Ledger Entry",
      description: "Posts debit to selected expense account",
      targetModule: "finance",
      isCompensatable: true,
      executor: async (ctx) => ({
        success: true,
        actionId: "cascade_exp_entry",
        actionType: "record_expense",
        data: { amount: ctx.formData.amount_bdt, category: ctx.formData.cost_category },
        timestamp: new Date().toISOString(),
      }),
    },
  ],
  relatedEntitiesResolver: (data) => [
    {
      id: "exp_ledger",
      entityType: "expense",
      label: `Expense ৳${Number(data.amount_bdt || 0).toLocaleString()}`,
      url: "/dashboard/finance",
      module: "finance",
    },
  ],
};

export const RECEIVE_INCOME_TEMPLATE: WorkflowTemplate = {
  id: "wf_receive_income",
  code: "INC-01",
  title: "Receive Farm Revenue",
  shortDescription: "Record milk collection sales, organic manure revenue, or miscellaneous farm income",
  fullDescription: "Revenue entry workflow. Automatically credits bank or cash vaults and updates customer receipts.",
  category: "finance",
  icon: "CircleDollarSign",
  estimatedTimeMinutes: 2,
  tags: ["income", "revenue", "milk", "sales", "finance"],
  roleAccess: ["owner", "manager", "accountant"],
  isPinned: false,
  isFavorite: true,
  clickReductionRatio: "1 step vs 10 clicks",
  timeOfDaySuggestion: "morning",
  steps: [
    {
      id: "step_inc_main",
      title: "Revenue Details",
      description: "Enter income stream and collected amount",
      fields: [
        {
          id: "income_source",
          name: "income_source",
          label: "Revenue Source",
          type: "select",
          required: true,
          options: [
            { label: "Raw Milk Daily Collection", value: "milk_sales" },
            { label: "Compost & Organic Manure", value: "manure_sales" },
            { label: "Consultancy & Breeding Services", value: "services" },
          ],
        },
        {
          id: "amount_bdt",
          name: "amount_bdt",
          label: "Amount Received (BDT)",
          type: "currency",
          required: true,
          placeholder: "e.g. 35000",
        },
      ],
    },
  ],
  cascadeActions: [
    {
      id: "cascade_inc_entry",
      type: "record_income",
      name: "Income Journal Entry",
      description: "Credits revenue ledger and updates cash balance",
      targetModule: "finance",
      isCompensatable: true,
      executor: async (ctx) => ({
        success: true,
        actionId: "cascade_inc_entry",
        actionType: "record_income",
        data: { amount: ctx.formData.amount_bdt, source: ctx.formData.income_source },
        timestamp: new Date().toISOString(),
      }),
    },
  ],
  relatedEntitiesResolver: (data) => [
    {
      id: "inc_record",
      entityType: "income",
      label: `Income ৳${Number(data.amount_bdt || 0).toLocaleString()}`,
      url: "/dashboard/finance",
      module: "finance",
    },
  ],
};
