import { WorkflowTemplate } from "./types";

export const VACCINATION_TEMPLATE: WorkflowTemplate = {
  id: "wf_vaccination",
  code: "VACC-01",
  title: "Vaccination & Immunization Protocol",
  shortDescription: "Administer scheduled vaccine, record vial usage, and schedule booster",
  fullDescription: "Standard veterinary protocol to record immunization (FMD, Anthrax, BQ, Deworming). Automatically reduces vaccine vial stock and auto-schedules next booster.",
  category: "livestock",
  icon: "ShieldAlert",
  estimatedTimeMinutes: 3,
  tags: ["vaccination", "veterinary", "health", "compliance"],
  roleAccess: ["owner", "manager", "veterinarian"],
  isPinned: true,
  isFavorite: true,
  clickReductionRatio: "2 steps vs 16 clicks",
  timeOfDaySuggestion: "morning",
  steps: [
    {
      id: "step_vacc_details",
      title: "Vaccine & Target Selection",
      description: "Specify cattle tag and vaccine type",
      fields: [
        {
          id: "cattle_tag",
          name: "cattle_tag",
          label: "Cattle Ear Tag #",
          type: "text",
          required: true,
          placeholder: "e.g. TAG-101",
        },
        {
          id: "vaccine_type",
          name: "vaccine_type",
          label: "Vaccine Type",
          type: "select",
          required: true,
          options: [
            { label: "FMD (Foot-and-Mouth Disease)", value: "fmd" },
            { label: "Anthrax (Spore Vaccine)", value: "anthrax" },
            { label: "Black Quarter (BQ)", value: "bq" },
            { label: "Broad Spectrum Dewormer", value: "deworming" },
          ],
        },
        {
          id: "dosage_ml",
          name: "dosage_ml",
          label: "Dosage (ml)",
          type: "number",
          required: true,
          defaultValue: 3,
        },
      ],
    },
    {
      id: "step_vacc_booster",
      title: "Booster Schedule",
      description: "Set booster interval",
      fields: [
        {
          id: "booster_days",
          name: "booster_days",
          label: "Schedule Booster Due (Days)",
          type: "number",
          defaultValue: 180,
        },
      ],
    },
  ],
  cascadeActions: [
    {
      id: "cascade_vacc_inventory",
      type: "update_inventory",
      name: "Medicine Stock Reduction",
      description: "Deducts medicine vial units",
      targetModule: "inventory",
      isCompensatable: true,
      executor: async (ctx) => ({
        success: true,
        actionId: "cascade_vacc_inventory",
        actionType: "update_inventory",
        data: { vaccine: ctx.formData.vaccine_type, dosesUsed: 1 },
        timestamp: new Date().toISOString(),
      }),
    },
    {
      id: "cascade_vacc_schedule",
      type: "schedule_health_protocol",
      name: "Schedule Next Booster",
      description: "Inserts next immunization milestone",
      targetModule: "livestock",
      isCompensatable: true,
      executor: async (ctx) => ({
        success: true,
        actionId: "cascade_vacc_schedule",
        actionType: "schedule_health_protocol",
        data: { boosterDays: ctx.formData.booster_days },
        timestamp: new Date().toISOString(),
      }),
    },
  ],
  relatedEntitiesResolver: (data) => [
    {
      id: String(data.cattle_tag || "TAG-101"),
      entityType: "cattle",
      label: `Cattle: ${data.cattle_tag || "TAG-101"}`,
      url: "/dashboard/cattle",
      module: "livestock",
    },
  ],
};

export const MEDICINE_USAGE_TEMPLATE: WorkflowTemplate = {
  id: "wf_medicine_usage",
  code: "MED-01",
  title: "Medicine & Health Treatment Usage",
  shortDescription: "Record clinical diagnosis, medication dosage, and inventory deduction",
  fullDescription: "Veterinary clinical treatment workflow. Records diagnosis, administered drugs, and reduces medicine inventory.",
  category: "livestock",
  icon: "HeartPulse",
  estimatedTimeMinutes: 3,
  tags: ["treatment", "medicine", "veterinary", "health"],
  roleAccess: ["owner", "manager", "veterinarian"],
  isPinned: false,
  isFavorite: true,
  clickReductionRatio: "2 steps vs 15 clicks",
  timeOfDaySuggestion: "anytime",
  steps: [
    {
      id: "step_med_treatment",
      title: "Clinical Treatment Details",
      description: "Specify patient tag and medication",
      fields: [
        {
          id: "cattle_tag",
          name: "cattle_tag",
          label: "Cattle Ear Tag #",
          type: "text",
          required: true,
          placeholder: "e.g. TAG-105",
        },
        {
          id: "diagnosis",
          name: "diagnosis",
          label: "Condition",
          type: "select",
          required: true,
          options: [
            { label: "Bovine Respiratory Disease", value: "pneumonia" },
            { label: "Bloat / Ruminal Acidosis", value: "bloat" },
            { label: "Foot Rot / Lesion", value: "foot_rot" },
          ],
        },
        {
          id: "medicine_id",
          name: "medicine_id",
          label: "Medicine",
          type: "select",
          required: true,
          options: [
            { label: "Oxytetracycline LA 20%", value: "med_oxy" },
            { label: "Flunixin Meglumine", value: "med_flunixin" },
          ],
        },
      ],
    },
  ],
  cascadeActions: [
    {
      id: "cascade_med_inventory",
      type: "update_inventory",
      name: "Pharmacy Stock Deduction",
      description: "Deducts medicine units",
      targetModule: "inventory",
      isCompensatable: true,
      executor: async (ctx) => ({
        success: true,
        actionId: "cascade_med_inventory",
        actionType: "update_inventory",
        entityId: String(ctx.formData.medicine_id || "med_oxy"),
        timestamp: new Date().toISOString(),
      }),
    },
  ],
  relatedEntitiesResolver: (data) => [
    {
      id: String(data.cattle_tag || "TAG-105"),
      entityType: "cattle",
      label: `Cattle: ${data.cattle_tag || "TAG-105"}`,
      url: "/dashboard/cattle",
      module: "livestock",
    },
  ],
};
