-- ============================================================================
-- Feed inventory ledger: one source of truth for stock quantity and cost.
-- Design: docs/FEED_SYSTEM_ARCHITECTURE.md. Rollback: supabase/rollback/20260925100000_feed_inventory_ledger_down.sql
--
-- Additive only: no column dropped, no row deleted, no existing quantity/cost changed.
-- Existing rows get a movement_type classification (derived from type + notes) and
-- a cost_source label; every non-trivial classification is written to the audit table.
-- Idempotent: safe to re-run.
-- ============================================================================
begin;

-- ── 1. Movement meaning, idempotency, cost provenance ────────────────────────────
alter table public.inventory_transactions
  add column if not exists movement_type   text,
  add column if not exists idempotency_key text,
  add column if not exists reverses_id     uuid references public.inventory_transactions(id),
  add column if not exists cost_source     text,
  add column if not exists is_estimate     boolean not null default false,
  add column if not exists created_by      uuid,
  -- set only on rows posted by a feed usage period (FK added by 20260925130000)
  add column if not exists period_line_id  uuid;

-- Precision (money must not be cut to 2 decimals mid-calculation): qty numeric(10,2) and
-- unit_cost numeric(12,2) stored ৳3000/128 pieces as ৳23.44 instead of ৳23.4375. Widening the
-- scale changes no existing value. Totals are rounded to 2 decimals only when presented/posted.
do $$
begin
  if (select numeric_scale from information_schema.columns
      where table_schema = 'public' and table_name = 'inventory_transactions' and column_name = 'unit_cost') < 6 then
    drop view if exists public.v_inventory_balance;   -- recreated below
    alter table public.inventory_transactions
      alter column qty type numeric(14,4),
      alter column unit_cost type numeric(14,6);
  end if;
end $$;

comment on column public.inventory_transactions.type is
  'Direction only: purchase = stock IN, consumption = stock OUT. Meaning lives in movement_type.';
comment on column public.inventory_transactions.movement_type is
  'purchase | opening_balance | own_production | feed_mix_output | adjustment_in | return | consumption_reversal (IN); consumption | feed_mix_input | wastage | adjustment_out | purchase_reversal (OUT). purchase_reversal = audited undo of a purchase row entered by mistake (reverses_id, same cost). own_production = harvested from own/leased land (not cash); consumption_reversal = audited undo of a consumption row (reverses_id).';
comment on column public.inventory_transactions.is_estimate is
  'true = quantity was generated by a formula (legacy auto-deduction), not recorded from physical feeding';

-- ── 2. Audit table for classifications and corrections ───────────────────────────
create table if not exists public.inventory_ledger_audit (
  id               uuid primary key default gen_random_uuid(),
  transaction_id   uuid references public.inventory_transactions(id),
  action           text not null check (action in ('classify','fill_missing_cost','insert_correction','rollback')),
  correction_batch text not null,
  field            text,
  old_value        text,
  new_value        text,
  reason           text not null,
  evidence         text,
  created_at       timestamptz not null default now(),
  created_by       uuid
);
create index if not exists idx_inventory_ledger_audit_tx on public.inventory_ledger_audit(transaction_id);
alter table public.inventory_ledger_audit enable row level security;
drop policy if exists "ledger audit readable by tenant" on public.inventory_ledger_audit;
create policy "ledger audit readable by tenant" on public.inventory_ledger_audit
  for select using (
    transaction_id in (
      select t.id from public.inventory_transactions t
      join public.inventory_items i on i.id = t.item_id
      where i.business_id in (
        select id from public.businesses where owner_id = auth.uid()
        union
        select business_id from public.business_users where user_id = auth.uid()
      )
    )
  );
-- No insert/update/delete policies: only migrations / service role write the audit trail.

-- ── 3. Backfill classification of existing rows (only where not yet classified) ──
with classified as (
  select t.id,
    case
      when t.type = 'purchase' and n.notes ilike 'Initial stock%'          then 'opening_balance'
      when t.type = 'purchase' and n.notes ilike 'Mixed feed produced%'    then 'feed_mix_output'
      when t.type = 'purchase' and n.notes ilike 'True-Up%'                then 'adjustment_in'
      when t.type = 'purchase' and n.notes ilike 'Stock Adjustment%'       then 'adjustment_in'
      when t.type = 'purchase'                                             then 'purchase'
      when n.notes ilike 'Feed mix%' or n.notes ilike 'Batch production%'  then 'feed_mix_input'
      when n.notes ilike '[FEED WASTE%'                                    then 'wastage'
      when n.notes ilike 'True-Up%' or n.notes ilike 'Stock Adjustment%'   then 'adjustment_out'
      else 'consumption'
    end as mt,
    (n.notes ilike 'Auto-Feed Deduction%' or n.notes ilike 'Daily batch deduction%') as est
  from public.inventory_transactions t
  cross join lateral (select coalesce(t.notes, '') as notes) n
  where t.movement_type is null
),
upd as (
  update public.inventory_transactions t
  set movement_type = c.mt, is_estimate = c.est
  from classified c where c.id = t.id
  returning t.id, t.movement_type, t.is_estimate, t.notes
)
insert into public.inventory_ledger_audit (transaction_id, action, correction_batch, field, old_value, new_value, reason, evidence)
select id, 'classify', '20260925-ledger-backfill', 'movement_type', null, movement_type,
       case when movement_type = 'opening_balance' then 'Opening stock is not a cash purchase (P-08 / C2)'
            when is_estimate then 'Legacy formula-generated deduction, flagged as estimate (P-01)'
            else 'Reclassified from type + notes' end,
       left(coalesce(notes, ''), 120)
from upd
where movement_type not in ('purchase', 'consumption') or is_estimate;

-- cost provenance for existing rows (labels only; values untouched)
update public.inventory_transactions set cost_source =
  case
    when unit_cost is null                          then 'missing'
    when type = 'purchase' and unit_cost = 0        then 'zero_unconfirmed'
    when type = 'purchase'                          then 'invoice'
    else 'legacy'
  end
where cost_source is null;

-- ── 4. Constraints (NOT VALID first, then validate: existing data was checked clean) ──
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'inventory_tx_movement_type_chk') then
    alter table public.inventory_transactions add constraint inventory_tx_movement_type_chk
      check (movement_type in ('purchase','opening_balance','own_production','feed_mix_output','adjustment_in','return','consumption_reversal',
                               'consumption','feed_mix_input','wastage','adjustment_out','purchase_reversal')) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'inventory_tx_direction_chk') then
    alter table public.inventory_transactions add constraint inventory_tx_direction_chk
      check ((type = 'purchase') = (movement_type in ('purchase','opening_balance','own_production','feed_mix_output','adjustment_in','return','consumption_reversal'))) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'inventory_tx_cost_source_chk') then
    alter table public.inventory_transactions add constraint inventory_tx_cost_source_chk
      check (cost_source in ('invoice','wac','mix_inputs','zero_confirmed','zero_unconfirmed','missing','manual','legacy','correction')) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'inventory_tx_qty_positive_chk') then
    alter table public.inventory_transactions add constraint inventory_tx_qty_positive_chk check (qty > 0) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'inventory_tx_unit_cost_nonneg_chk') then
    alter table public.inventory_transactions add constraint inventory_tx_unit_cost_nonneg_chk check (unit_cost is null or unit_cost >= 0) not valid;
  end if;
end $$;
alter table public.inventory_transactions validate constraint inventory_tx_movement_type_chk;
alter table public.inventory_transactions validate constraint inventory_tx_direction_chk;
alter table public.inventory_transactions validate constraint inventory_tx_cost_source_chk;
alter table public.inventory_transactions validate constraint inventory_tx_qty_positive_chk;
alter table public.inventory_transactions validate constraint inventory_tx_unit_cost_nonneg_chk;
alter table public.inventory_transactions alter column movement_type set not null;
alter table public.inventory_transactions alter column cost_source set not null;

-- one physical event = one row (P-02). Keys are business-scoped by the writer.
create unique index if not exists uq_inventory_tx_idempotency
  on public.inventory_transactions(idempotency_key) where idempotency_key is not null;
create index if not exists idx_inventory_tx_item_date on public.inventory_transactions(item_id, recorded_at);
create index if not exists idx_inventory_tx_movement on public.inventory_transactions(movement_type);

-- ── 5. Units (P-03) ─────────────────────────────────────────────────────────────
alter table public.inventory_items
  add column if not exists kg_per_unit numeric;
comment on column public.inventory_items.kg_per_unit is
  'How many kg one stock unit weighs (e.g. 1 piece of straw = X kg). NULL = unknown: the system must not convert.';
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'inventory_items_kg_per_unit_chk') then
    alter table public.inventory_items add constraint inventory_items_kg_per_unit_chk
      check (kg_per_unit is null or kg_per_unit > 0);
  end if;
end $$;
-- kg items weigh 1 kg per unit by definition; everything else stays unknown until the owner sets it.
update public.inventory_items set kg_per_unit = 1 where lower(unit) = 'kg' and kg_per_unit is null;
create or replace function public.trg_inventory_items_kg_default() returns trigger language plpgsql as $$
begin
  if lower(new.unit) = 'kg' and new.kg_per_unit is null then new.kg_per_unit := 1; end if;
  return new;
end $$;
drop trigger if exists trg_inventory_items_kg_default on public.inventory_items;
create trigger trg_inventory_items_kg_default before insert or update of unit, kg_per_unit on public.inventory_items
  for each row execute function public.trg_inventory_items_kg_default();

-- ── 6. Recipe integrity (Rule 3/4) ──────────────────────────────────────────────
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'feed_recipes_output_qty_pos_chk') then
    alter table public.feed_recipes add constraint feed_recipes_output_qty_pos_chk check (output_qty > 0) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'recipe_ingredients_qty_pos_chk') then
    alter table public.recipe_ingredients add constraint recipe_ingredients_qty_pos_chk check (qty_per_batch > 0) not valid;
  end if;
end $$;
alter table public.feed_recipes validate constraint feed_recipes_output_qty_pos_chk;
alter table public.recipe_ingredients validate constraint recipe_ingredients_qty_pos_chk;

create or replace function public.assert_recipe_balanced(p_recipe_id uuid)
returns void language plpgsql as $$
declare v_out numeric; v_sum numeric; v_active boolean;
begin
  select output_qty, is_active into v_out, v_active from public.feed_recipes where id = p_recipe_id;
  if not found or not coalesce(v_active, false) then return; end if;   -- only ACTIVE recipes must balance
  select coalesce(sum(qty_per_batch), 0) into v_sum from public.recipe_ingredients where recipe_id = p_recipe_id;
  if abs(v_sum - v_out) > 0.01 then
    raise exception 'Recipe % is active but its ingredients total % kg while the batch size is % kg', p_recipe_id, v_sum, v_out
      using errcode = 'check_violation';
  end if;
end $$;

create or replace function public.trg_recipe_balanced() returns trigger language plpgsql as $$
begin
  if tg_table_name = 'feed_recipes' then
    perform public.assert_recipe_balanced(new.id);
  elsif tg_op = 'DELETE' then
    perform public.assert_recipe_balanced(old.recipe_id);
  else
    perform public.assert_recipe_balanced(new.recipe_id);
  end if;
  return null;
end $$;

drop trigger if exists trg_feed_recipes_balanced on public.feed_recipes;
create constraint trigger trg_feed_recipes_balanced
  after insert or update of is_active, output_qty on public.feed_recipes
  deferrable initially deferred for each row execute function public.trg_recipe_balanced();
drop trigger if exists trg_recipe_ingredients_balanced on public.recipe_ingredients;
create constraint trigger trg_recipe_ingredients_balanced
  after insert or update or delete on public.recipe_ingredients
  deferrable initially deferred for each row execute function public.trg_recipe_balanced();

-- ── 7. Costing: perpetual moving-average cost as of a date (P-04) ─────────────
-- cost(item, d) = value on hand / quantity on hand, over movements with a known cost
-- dated on or before d. Every OUT row removes value at the average of its moment (its
-- stored unit_cost), so the average always describes the stock that is really left:
--   100 kg @ ৳40 + 200 kg @ ৳50 on hand → ৳46.67;  100 @ ৳40 used up, then 100 @ ৳60 → ৳60
-- (a cumulative average of every purchase ever made would say ৳50 and leave book value on
-- an empty store). Undone purchases and undone consumption move value like any other row.
-- With nothing on hand (or unknown value) the last known stock-in price is used.
-- A movement dated after d never changes the cost as of d.
create or replace function public.inventory_unit_cost_as_of(p_item_id uuid, p_as_of date)
returns numeric language sql stable as $$
  with m as (
    select sum(case when type = 'purchase' then qty else -qty end) as q,
           sum(case when type = 'purchase' then qty * unit_cost else -qty * unit_cost end) as v
    from public.inventory_transactions
    where item_id = p_item_id and recorded_at <= p_as_of
      and unit_cost is not null and cost_source <> 'missing'
  )
  select case
    when m.q > 0.0001 and m.v >= 0 then round(m.v / m.q, 6)
    else (select t.unit_cost from public.inventory_transactions t
          where t.item_id = p_item_id and t.recorded_at <= p_as_of
            and t.movement_type in ('purchase', 'opening_balance', 'own_production', 'feed_mix_output', 'adjustment_in', 'return')
            and t.unit_cost is not null and t.cost_source <> 'missing'
          order by t.recorded_at desc, t.created_at desc limit 1)
  end
  from m
$$;

-- ── 8. Insert-time rules: default classification, cost, stock guard ──────────────
create or replace function public.trg_inventory_tx_before_insert() returns trigger language plpgsql as $$
declare v_balance numeric;
begin
  -- default meaning from direction for writers that don't set it
  if new.movement_type is null then
    new.movement_type := case when new.type = 'purchase' then 'purchase' else 'consumption' end;
  end if;

  -- serialise all movements of one item (concurrency: no double spend)
  perform pg_advisory_xact_lock(hashtextextended(new.item_id::text, 0));

  if new.type = 'consumption' then
    -- a purchase_reversal must undo a purchase row of the same item, at that row's cost
    if new.movement_type = 'purchase_reversal' then
      if new.reverses_id is null or not exists (select 1 from public.inventory_transactions o
          where o.id = new.reverses_id and o.item_id = new.item_id and o.movement_type = 'purchase' and o.qty >= new.qty) then
        raise exception 'purchase_reversal must reference a purchase row of the same item with at least this quantity'
          using errcode = 'check_violation';
      end if;
      select unit_cost, cost_source into new.unit_cost, new.cost_source
      from public.inventory_transactions where id = new.reverses_id;
    -- OUT movements are valued at WAC as of their date unless a manual cost is declared
    elsif coalesce(new.cost_source, '') <> 'manual' then
      new.unit_cost := public.inventory_unit_cost_as_of(new.item_id, new.recorded_at::date);
      new.cost_source := case when new.unit_cost is null then 'missing' else 'wac' end;
    end if;
    -- stock guard: signed balance of every movement for this item (no clamping, no sign tricks).
    -- A usage-period posting is computed from the stock available AS OF its end date by the
    -- period reconciliation itself, so the all-dates balance check does not apply to it.
    if new.period_line_id is not null then return new; end if;
    select coalesce(sum(case when type = 'purchase' then qty else -qty end), 0) into v_balance
    from public.inventory_transactions where item_id = new.item_id;
    if v_balance - new.qty < -0.0001 then
      raise exception 'Insufficient stock for item %: on hand %, requested %', new.item_id, round(v_balance, 4), new.qty
        using errcode = 'check_violation';
    end if;
  else
    if new.cost_source is null then
      new.cost_source := case
        when new.movement_type = 'feed_mix_output' then 'mix_inputs'
        -- grass from own/leased land: the land cost is an expense (Rent & Lease), so the fodder
        -- itself carries no cost here — valuing it too would count the land cost twice
        when new.movement_type = 'own_production' and coalesce(new.unit_cost, 0) = 0 then 'zero_confirmed'
        when new.unit_cost is null and new.movement_type in ('adjustment_in','return') then 'wac'
        when new.unit_cost is null then 'missing'
        when new.unit_cost = 0 then 'zero_unconfirmed'
        else 'invoice' end;
    end if;
    if new.movement_type = 'own_production' and new.unit_cost is null then
      new.unit_cost := 0;
    end if;
    -- a reversal must point at the consumption row it undoes and carry that row's cost
    if new.movement_type = 'consumption_reversal' then
      if new.reverses_id is null or not exists (select 1 from public.inventory_transactions o
          where o.id = new.reverses_id and o.item_id = new.item_id and o.type = 'consumption' and o.qty >= new.qty) then
        raise exception 'consumption_reversal must reference a consumption row of the same item with at least this quantity'
          using errcode = 'check_violation';
      end if;
      -- an undo gives back the value that row took out; only an explicit, audited correction
      -- may state its own cost (e.g. ৳0 for quantity that never existed)
      if new.unit_cost is null then
        select unit_cost into new.unit_cost from public.inventory_transactions where id = new.reverses_id;
        -- the generic IN default above marked it 'missing' (no cost yet); it now has the original's cost
        new.cost_source := case when new.unit_cost is null then 'missing' else 'correction' end;
      end if;
    end if;
    if new.unit_cost is null and new.movement_type in ('adjustment_in','return') then
      new.unit_cost := public.inventory_unit_cost_as_of(new.item_id, new.recorded_at::date);
      if new.unit_cost is null then new.cost_source := 'missing'; end if;
    end if;
  end if;
  return new;
end $$;

-- the old guard (20260626) ignored negative-qty purchases and took no lock: replace it
drop trigger if exists trg_check_inventory_stock on public.inventory_transactions;
drop trigger if exists trg_inventory_tx_before_insert on public.inventory_transactions;
create trigger trg_inventory_tx_before_insert
  before insert on public.inventory_transactions
  for each row execute function public.trg_inventory_tx_before_insert();

-- ── 9. Signed stock & value view (P-05: negatives are visible) ──────────────────
create or replace view public.v_inventory_balance
with (security_invoker = true) as
select i.id as item_id, i.business_id, i.name, i.unit, i.category, i.kg_per_unit,
       coalesce(sum(case when t.type = 'purchase' then t.qty else -t.qty end), 0)                          as qty_on_hand,
       coalesce(sum(case when t.type = 'purchase' then t.qty * coalesce(t.unit_cost,0)
                         else -t.qty * coalesce(t.unit_cost,0) end), 0)                                    as value_on_hand,
       count(*) filter (where t.cost_source = 'missing')                                                   as rows_missing_cost,
       count(*) filter (where t.cost_source = 'zero_unconfirmed')                                          as rows_zero_unconfirmed,
       count(*) filter (where t.is_estimate)                                                               as rows_estimated
from public.inventory_items i
left join public.inventory_transactions t on t.item_id = i.id
where i.deleted_at is null
group by i.id;

-- ── 9b. Per-animal consumption net of audited reversals (used by the accounting engine) ──
create or replace function public.get_cattle_consumptions(p_business_id uuid)
returns table (cattle_id uuid, category text, total_cost numeric) language plpgsql as $$
begin
  return query
  select it.cattle_id, i.category::text,
         sum(case when it.movement_type = 'consumption_reversal' then -1 else 1 end * it.qty * coalesce(it.unit_cost, 0))
  from public.inventory_transactions it
  join public.inventory_items i on i.id = it.item_id
  where i.business_id = p_business_id
    and it.cattle_id is not null
    and (it.type = 'consumption' or it.movement_type = 'consumption_reversal')
  group by it.cattle_id, i.category;
end $$;

-- current unit cost of every item — the ONE place pages read cost from (no app-side averages)
create or replace view public.v_inventory_unit_cost with (security_invoker = true) as
select i.id as item_id, i.business_id,
       public.inventory_unit_cost_as_of(i.id, (now() at time zone 'Asia/Dhaka')::date) as unit_cost
from public.inventory_items i
where i.deleted_at is null;

-- ── 10. Explicit daily feeding (replaces page-load auto-deduction) ─────────────────
-- One call records one herd feeding for one date. The idempotency key makes a second
-- call for the same business/date/item fail instead of deducting twice.
create or replace function public.record_herd_feeding(
  p_business_id uuid, p_date date, p_lines jsonb, p_note text default null
) returns integer language plpgsql security invoker as $$
declare v_line jsonb; v_count int := 0;
begin
  for v_line in select * from jsonb_array_elements(p_lines) loop
    if (v_line->>'qty')::numeric <= 0 then continue; end if;
    if not exists (select 1 from public.inventory_items
                   where id = (v_line->>'item_id')::uuid and business_id = p_business_id) then
      raise exception 'Item % does not belong to this business', v_line->>'item_id' using errcode = '42501';
    end if;
    insert into public.inventory_transactions
      (item_id, type, movement_type, qty, recorded_at, notes, idempotency_key, created_by)
    values ((v_line->>'item_id')::uuid, 'consumption', 'consumption', (v_line->>'qty')::numeric, p_date,
            coalesce(p_note, 'Daily herd feeding (recorded)'),
            'herd-feeding:' || p_business_id || ':' || p_date || ':' || (v_line->>'item_id'),
            auth.uid());
    v_count := v_count + 1;
  end loop;
  return v_count;
end $$;
revoke all on function public.record_herd_feeding(uuid, date, jsonb, text) from public, anon;
grant execute on function public.record_herd_feeding(uuid, date, jsonb, text) to authenticated, service_role;

-- ── 11. Feed mixing as an internal transformation (P-03/F-03, F-01, F-11) ────────
-- Ingredients scale by the recipe's own ingredient total (= batch size); inputs are
-- feed_mix_input at WAC; the output is feed_mix_output valued at the inputs' cost.
-- Never a purchase, never cash. One transaction; idempotent per batch id.
create or replace function public.produce_feed_batch(
  p_business_id uuid, p_recipe_id uuid, p_output_item_id uuid, p_output_qty numeric, p_date date, p_batch_id uuid
) returns numeric language plpgsql security invoker as $$
declare v_sum numeric; v_ing record; v_in_qty numeric; v_cost numeric := 0; v_row_cost numeric; v_name text;
        v_missing boolean := false;
begin
  if p_output_qty <= 0 then raise exception 'Batch quantity must be > 0' using errcode = 'check_violation'; end if;
  select name into v_name from public.feed_recipes where id = p_recipe_id and business_id = p_business_id;
  if not found then raise exception 'Recipe not found' using errcode = '42501'; end if;
  if not exists (select 1 from public.inventory_items where id = p_output_item_id and business_id = p_business_id) then
    raise exception 'Output item not found' using errcode = '42501';
  end if;
  select coalesce(sum(qty_per_batch), 0) into v_sum from public.recipe_ingredients where recipe_id = p_recipe_id;
  if v_sum <= 0 then raise exception 'Recipe has no ingredients' using errcode = 'check_violation'; end if;

  for v_ing in select item_id, qty_per_batch from public.recipe_ingredients where recipe_id = p_recipe_id loop
    v_in_qty := round(v_ing.qty_per_batch / v_sum * p_output_qty, 4);
    insert into public.inventory_transactions (item_id, type, movement_type, qty, recorded_at, notes, idempotency_key, created_by)
    values (v_ing.item_id, 'consumption', 'feed_mix_input', v_in_qty, p_date,
            'Feed mix input: ' || v_name || ' ×' || p_output_qty || ' kg',
            'feed-batch:' || p_batch_id || ':in:' || v_ing.item_id, auth.uid())
    returning unit_cost into v_row_cost;
    if v_row_cost is null then v_missing := true; end if;   -- ingredient has no known cost yet
    v_cost := v_cost + v_in_qty * coalesce(v_row_cost, 0);
  end loop;

  insert into public.inventory_transactions (item_id, type, movement_type, qty, unit_cost, cost_source, recorded_at, notes, idempotency_key, created_by)
  -- an unknown ingredient cost makes the batch cost unknown: never value it as if that input were free
  values (p_output_item_id, 'purchase', 'feed_mix_output', p_output_qty,
          case when v_missing then null else round(v_cost / p_output_qty, 6) end,
          case when v_missing then 'missing' else 'mix_inputs' end, p_date,
          'Feed mix output: ' || v_name || ' ×' || p_output_qty || ' kg',
          'feed-batch:' || p_batch_id || ':out', auth.uid());
  return case when v_missing then null else round(v_cost, 2) end;
end $$;
revoke all on function public.produce_feed_batch(uuid, uuid, uuid, numeric, date, uuid) from public, anon;
grant execute on function public.produce_feed_batch(uuid, uuid, uuid, numeric, date, uuid) to authenticated, service_role;

commit;
