import { NextRequest, NextResponse } from "next/server";
import { authenticateApiRoute } from "@/lib/auth/api-guard";
import { AiAutomationEngine } from "@/lib/ai/automation-engine";
import { AiAuditService } from "@/lib/ai/audit-service";
import { PERMISSIONS } from "@/constants/roles";

export async function GET(req: NextRequest) {
  try {
    const authResult = await authenticateApiRoute(req, {
      requiredPermission: PERMISSIONS.REPORTS_VIEW,
      rateLimitConfig: { maxRequests: 30, windowMs: 60_000 },
    });
    if ("response" in authResult) return authResult.response;
    const { auth } = authResult;
    if (auth.type !== "user") return NextResponse.json({ error: "User session required" }, { status: 401 });
    const { businessId } = auth.context;
    const pending = AiAutomationEngine.getPendingProposals(businessId);
    return NextResponse.json({ success: true, proposals: pending });
  } catch (error: unknown) {
    return NextResponse.json({ error: error instanceof Error ? error.message : "Error" }, { status: 500 });
  }
}

export async function POST(req: NextRequest) {
  try {
    const authResult = await authenticateApiRoute(req, {
      requiredPermission: PERMISSIONS.SETTINGS_EDIT,
      rateLimitConfig: { maxRequests: 20, windowMs: 60_000 },
    });
    if ("response" in authResult) return authResult.response;
    const { auth } = authResult;
    if (auth.type !== "user") return NextResponse.json({ error: "User session required" }, { status: 401 });
    const { businessId, user } = auth.context;

    const body = await req.json();
    const { action, proposalId, reason, notes, proposalPayload } = body;

    if (action === "propose") {
      const proposal = AiAutomationEngine.proposeAutomation({
        businessId,
        actionType: proposalPayload.actionType,
        title: proposalPayload.title,
        description: proposalPayload.description,
        urgency: proposalPayload.urgency || "ACTION_REQUIRED",
        parameters: proposalPayload.parameters || {},
        confidenceScore: proposalPayload.confidenceScore || 0.9,
        reasoning: proposalPayload.reasoning || "Generated by AI supervisor",
      });
      return NextResponse.json({ success: true, proposal });
    }

    if (action === "approve") {
      if (!proposalId) return NextResponse.json({ error: "proposalId is required" }, { status: 400 });
      const execution = await AiAutomationEngine.approveAndExecute(proposalId, user.id, notes);
      return NextResponse.json({ success: true, execution });
    }

    if (action === "reject") {
      if (!proposalId) return NextResponse.json({ error: "proposalId is required" }, { status: 400 });
      const proposal = AiAutomationEngine.rejectProposal(proposalId, user.id, reason || "Rejected by user");
      return NextResponse.json({ success: true, proposal });
    }

    return NextResponse.json({ error: `Unsupported action: ${action}` }, { status: 400 });
  } catch (error: unknown) {
    return NextResponse.json({ error: error instanceof Error ? error.message : "Error" }, { status: 500 });
  }
}
